#pragma once

#include <array>
#include <cstdint>
#include <filesystem>
#include <string>
#include <vector>

#include <openvdb/openvdb.h>

#include "genmesh/exit_code.h"

namespace genmesh {

/// Triangle with 3 vertex indices.
struct Triangle {
    uint32_t v0, v1, v2;
};

/// Extracted mesh data from volumeToMesh.
struct MeshData {
    std::vector<openvdb::Vec3s> points;   // world-space vertices
    std::vector<Triangle> triangles;      // all triangles (original + from quads)
    int64_t original_tri_count = 0;       // triangles directly from volumeToMesh
    int64_t original_quad_count = 0;      // quads from volumeToMesh (each → 2 tris)
    int64_t degenerate_count = 0;         // triangles with degenerate normals
};

/// Result of mesh extraction.
struct MeshResult {
    MeshData mesh;
    bool ok = false;
    ExitCode exit_code = ExitCode::Success;
    std::string error_code;
    std::string error_msg;
};

/// Extract isosurface mesh from a VDB grid.
///
/// Calls volumeToMesh, then splits quads into triangles per §7.1:
///   quad (0,1,2,3) → tri (0,1,2) + tri (0,2,3)
///
/// Counts degenerate triangles (|cross| < epsilon → normal = (0,0,0)).
MeshResult extract_mesh(const openvdb::FloatGrid::Ptr& grid,
                        double iso = 0.0,
                        double adaptivity = 0.0);

/// Result of STL write operation.
struct StlWriteResult {
    bool ok = false;
    ExitCode exit_code = ExitCode::Success;
    std::string error_code;
    std::string error_msg;
};

/// Write mesh to binary STL file.
///
/// - 80B header: "Generated by genmesh" + zero padding (§7.1)
/// - Normal: normalize(cross(v1-v0, v2-v0)), degenerate → (0,0,0)
/// - Atomic: writes to temp file (.tmp), then renames
StlWriteResult write_stl(const std::filesystem::path& path,
                         const MeshData& mesh);

/// Result of VDB write operation.
struct VdbWriteResult {
    bool ok = false;
    ExitCode exit_code = ExitCode::Success;
    std::string error_code;
    std::string error_msg;
};

/// Write VDB grid to file using openvdb::io::File.
VdbWriteResult write_vdb(const std::filesystem::path& path,
                         const openvdb::FloatGrid::Ptr& grid);

}  // namespace genmesh
