/// Preview shader composition: merge user SDF function with the raymarch template.
///
/// Reuses `sdf_baker::shader_compose::{load_shader, glsl_to_wgsl, validate_wgsl}`.
use anyhow::{Result, bail};
use sdf_baker::shader_compose::{ShaderLang, validate_wgsl};

const RAYMARCH_TEMPLATE_WGSL: &str = include_str!("shaders/raymarch_template.wgsl");

const PLACEHOLDER: &str = "{{USER_SDF}}";

/// Compose a preview (raymarch) shader from user SDF code.
///
/// Returns a complete WGSL source ready for `device.create_shader_module()`.
/// Both WGSL and GLSL user SDFs produce WGSL output using the WGSL template.
pub fn compose_preview(lang: ShaderLang, user_sdf_code: &str) -> Result<String> {
    match lang {
        ShaderLang::Wgsl => {
            let wgsl = RAYMARCH_TEMPLATE_WGSL.replace(PLACEHOLDER, user_sdf_code);
            validate_wgsl(&wgsl)?;
            Ok(wgsl)
        }
        ShaderLang::Glsl => {
            // Convert GLSL SDF function(s) to WGSL, then insert into WGSL template.
            // This avoids the problem of the GLSL template lacking a vertex shader.
            let wgsl_sdf = glsl_sdf_to_wgsl(user_sdf_code)?;
            let wgsl = RAYMARCH_TEMPLATE_WGSL.replace(PLACEHOLDER, &wgsl_sdf);
            validate_wgsl(&wgsl)?;
            Ok(wgsl)
        }
    }
}

/// Convert GLSL SDF function(s) to WGSL by wrapping in a minimal compute shader,
/// converting via naga, and extracting the user-defined functions.
///
/// # Why this approach is necessary
///
/// The preview renderer uses a single WGSL raymarch template (`raymarch_template.wgsl`)
/// containing both vertex (`vs_main`) and fragment (`fs_main`) entry points.
/// GLSL has no equivalent multi-stage template, so we cannot simply convert a
/// complete GLSL shader — naga would produce WGSL with mismatched entry points.
///
/// Instead, we:
/// 1. Wrap the user's GLSL SDF function(s) in a throwaway compute shader so
///    naga can parse valid GLSL (naga requires a complete shader stage).
/// 2. Convert the whole thing to WGSL via `glsl_to_wgsl()`.
/// 3. Extract only the user's function definitions from the naga output,
///    discarding the compute wrapper scaffolding.
/// 4. Insert the extracted WGSL functions into the WGSL raymarch template.
///
/// # naga output format dependency
///
/// Step 3 (`extract_user_functions`) relies on naga's WGSL output conventions:
/// - naga renames `void main()` → `fn main_1()` and emits a wrapper `fn main()`.
/// - User functions keep their original names (e.g. `fn sdf(...)`).
///
/// If a future naga version changes these conventions, the extraction will fail
/// and `test_compose_glsl_preview` / `test_glsl_sdf_to_wgsl_extracts_function`
/// will catch it. The naga version is pinned via `wgpu 27` in Cargo.toml.
fn glsl_sdf_to_wgsl(glsl_sdf: &str) -> Result<String> {
    // Wrap the user SDF in a minimal GLSL compute shader so naga can parse it.
    let wrapper = format!(
        "#version 450\n\
         layout(local_size_x = 1) in;\n\
         layout(std430, set = 0, binding = 0) buffer O {{ float d[]; }} o;\n\
         {glsl_sdf}\n\
         void main() {{ o.d[0] = sdf(vec3(0.0)); }}\n"
    );

    let full_wgsl = sdf_baker::shader_compose::glsl_to_wgsl(&wrapper)?;

    // The naga output has:
    //   struct O { d: array<f32>, }
    //   @group(0) @binding(0) var<storage, read_write> o: O;
    //   fn helper_1(...) { ... }   // if any
    //   fn sdf(...) { ... }
    //   @compute @workgroup_size(1) fn main() { ... }
    //
    // We extract all `fn` definitions except `fn main`.
    extract_user_functions(&full_wgsl)
}

/// Extract all function definitions from WGSL source, excluding the compute
/// wrapper functions (`fn main` and `fn main_1`) generated by naga.
///
/// This function depends on naga's naming convention for the entry point.
/// See [`glsl_sdf_to_wgsl`] for rationale and mitigation strategy.
fn extract_user_functions(wgsl: &str) -> Result<String> {
    let mut result = String::new();
    let mut search_from = 0;

    while search_from < wgsl.len() {
        let Some(fn_offset) = wgsl[search_from..].find("fn ") else {
            break;
        };
        let fn_pos = search_from + fn_offset;
        let after_fn = &wgsl[fn_pos + 3..];

        // Skip the wrapper's entry point and its body function.
        // naga renames `void main()` to `fn main_1()` and creates
        // `@compute fn main()` wrapper, so skip both.
        if after_fn.starts_with("main(")
            || after_fn.starts_with("main ")
            || after_fn.starts_with("main_1(")
            || after_fn.starts_with("main_1 ")
        {
            // Jump past this function
            if let Some(end) = find_matching_brace(wgsl, fn_pos) {
                search_from = end + 1;
            } else {
                break;
            }
            continue;
        }

        // Extract this user function
        if let Some(end) = find_matching_brace(wgsl, fn_pos) {
            result.push_str(&wgsl[fn_pos..=end]);
            result.push('\n');
            search_from = end + 1;
        } else {
            break;
        }
    }

    if result.is_empty() {
        bail!("No user functions found in GLSL→WGSL conversion output");
    }

    Ok(result)
}

/// Find the closing `}` that matches the first `{` at or after `start`.
fn find_matching_brace(s: &str, start: usize) -> Option<usize> {
    let bytes = s.as_bytes();
    let open = s[start..].find('{')? + start;
    let mut depth = 0;
    for i in open..bytes.len() {
        match bytes[i] {
            b'{' => depth += 1,
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    const SPHERE_WGSL: &str = r#"
fn sdf(p: vec3<f32>) -> f32 {
    return length(p - vec3<f32>(32.0, 32.0, 32.0)) - 25.6;
}
"#;

    const SPHERE_GLSL: &str = r#"
float sdf(vec3 p) {
    return length(p - vec3(32.0, 32.0, 32.0)) - 25.6;
}
"#;

    const CSG_GLSL: &str = r#"
float sdf(vec3 p) {
    vec3 center = vec3(64.0, 64.0, 64.0);
    vec3 q = p - center;
    float sphere = length(q) - 40.0;
    vec3 half_ext = vec3(25.0, 25.0, 25.0);
    vec3 d = abs(q) - half_ext;
    float box_d = length(max(d, vec3(0.0))) + min(max(d.x, max(d.y, d.z)), 0.0);
    return max(sphere, -box_d);
}
"#;

    #[test]
    fn test_compose_wgsl_preview() {
        let result = compose_preview(ShaderLang::Wgsl, SPHERE_WGSL);
        assert!(
            result.is_ok(),
            "WGSL preview composition failed: {result:?}"
        );
        let wgsl = result.unwrap();
        assert!(wgsl.contains("fn sdf("));
        assert!(wgsl.contains("fn vs_main("));
        assert!(wgsl.contains("fn fs_main("));
    }

    #[test]
    fn test_compose_glsl_preview() {
        let result = compose_preview(ShaderLang::Glsl, SPHERE_GLSL);
        assert!(
            result.is_ok(),
            "GLSL preview composition failed: {result:?}"
        );
        let wgsl = result.unwrap();
        // Must contain both entry points from the WGSL template
        assert!(wgsl.contains("fn vs_main("), "Missing vs_main");
        assert!(wgsl.contains("fn fs_main("), "Missing fs_main");
        // Must not contain the compute wrapper's main
        assert!(!wgsl.contains("@compute"), "Should not contain @compute");
    }

    #[test]
    fn test_compose_glsl_csg_preview() {
        let result = compose_preview(ShaderLang::Glsl, CSG_GLSL);
        assert!(
            result.is_ok(),
            "GLSL CSG preview composition failed: {result:?}"
        );
    }

    #[test]
    fn test_placeholder_replaced() {
        let wgsl = compose_preview(ShaderLang::Wgsl, SPHERE_WGSL).unwrap();
        assert!(!wgsl.contains(PLACEHOLDER));
    }

    #[test]
    fn test_glsl_sdf_to_wgsl_extracts_function() {
        let wgsl_sdf = glsl_sdf_to_wgsl(SPHERE_GLSL).unwrap();
        assert!(wgsl_sdf.contains("fn sdf("), "Extracted WGSL must contain sdf function");
        assert!(!wgsl_sdf.contains("fn main("), "Must not contain main");
    }
}
